### ISSUE TITLE
Replace "folderExclude" with "folderInclude" in file "adjustCopyright.py "

### ISSUE THREAD

**Issue by christianheller** [EnricoGallus/CybopBuildScripts#19]
In order to avoid changing files accidentally.

**Comment by EnricoGallus** [comment]
If files get changed accidentally, this indicates a bug in the algorithm and we should fix this issue.
Please have a little bit more confidence in the current implementation. It is much better than the first version and might have caused trouble.
Especially in a fast-paced and often changing source code like CYBOP, white-listing is much more error-prone than black-listing.
That's why I highly recommend not to make this change.

**Comment by christianheller** [comment]
I think it was some years ago in the "doc/" directory where the
copyright line of some 15 year old files (LaTeX or something)
of my book got changed with a new release, which is not wanted.

It is more effort to use blacklisting when including for instance
the "doc/" directory, having to exclude most sub directories.
But ok, as you wish, let's give the script another try :-)

(I reply to this issue via my email client and not the web portal
testwise, to see if it arrives in the github portal anyway.)


Am Freitag, 19. Mai 2023, 02:28:03 CEST schrieb EnricoGallus:
> If files get changed accidentally, this indicates a bug in the algorithm and we should fix this issue.
> Please have a little bit more confidence in the current implementation. It is much better than the first version and might have caused trouble.
> Especially in a fast-paced and often changing source code like CYBOP, white-listing is much more error-prone than black-listing.
> That's why I highly recommend not to make this change.
